### ISSUE TITLE
Error querying iTwin platform data

### ISSUE THREAD

**Issue by dv-anfimaude** [iTwin/iot-demo#189]
Hi guys, 
I've tried to  configured Visualizer to run locally as per this tutorial  https://github.com/iTwin/iot-demo/blob/master/IoTVisualizer/README.md
but faced with following error during app start
```
BE_SQLITE_ERROR: ECClass 'IoTDevice.devicepointobservesspatialelement' does not exist or could not be loaded.
    at DbQueryError.throwIfError (http://localhost:3000/static/js/vendors~main.chunk.js:267382:13)
    at ECSqlReader.runWithRetry (http://localhost:3000/static/js/vendors~main.chunk.js:268949:67)
    at async ECSqlReader.readRows (http://localhost:3000/static/js/vendors~main.chunk.js:268923:18)
    at async ECSqlReader.fetchRows (http://localhost:3000/static/js/vendors~main.chunk.js:268989:23)
    at async ECSqlReader.step (http://localhost:3000/static/js/vendors~main.chunk.js:269002:7)
    at async CheckpointConnection.query (http://localhost:3000/static/js/vendors~main.chunk.js:308957:12)
    at async push../src/IoTExtension/clients/ITwinLink.ts.ITwinLink.fetchDevices (http://localhost:3000/static/js/main.chunk.js:2759:22)
```

This is an error response from 
https://api.bentley.com/imodel/rpc//mode/1/context/265d3ac7-5f8e-48fa-91f0-577e8f897efc/imodel/b440b13e-5127-45e7-b71c-d0b07c82df23/changeset/0/IModelReadRpcInterface-3.4.0-queryRows
endpoint
There is also other similar error :
`ECClass 'RevitDynamic.level' does not exist or could not be loaded`

Visualizer app is unusable at this point . I see model but UI does not react to any click. 

I'am using Bentley Retail building sample template model. 

Please advice. 

cc   @tangytang

**Comment by tangytang** [comment]
@ashish-srivastava-dev any updates on the above? facing the same issue here.

**Comment by ashish-srivastava1** [comment]
I apologize for the delayed reply here. This repository is not currently under active development. The error was coming because the iModel is not provisioned with the IoT schema.
